#!/usr/bin/env python3
"""
Multi-site Agentic Framework using CrewAI
Converts EU agent topic generation to USA agent story writing across different server locations.
"""

import os
from crewai import Agent, Crew, Process, Task, LLM
from crewai.project import CrewBase, agent, crew, task


def main():
    # Initialize LLM objects for our custom endpoints
    llm_eu = LLM(
        model="openai/Qwen2.5-7B-Instruct-GGUF",
        base_url="http://9.163.149.120:61102/v1",
        api_key="local"
    )

    llm_usa = LLM(
        model="openai/Qwen2.5-7B-Instruct-GGUF",
        base_url="http://20.185.179.136:61100/v1",
        api_key="local"
    )

    # Define Agents
    eu_agent = Agent(
        role="Creative European Story Topic Generator",
        goal="Generate ONE creative and interesting story topic",
        backstory=(
            "You are a creative European storyteller with a flair for imaginative and unique ideas. "
            "Your specialty is generating compelling story topics that spark creativity and engagement. "
            "You focus on imaginative concepts that can form the basis of captivating narratives."
        ),
        llm=llm_eu,
        verbose=True,
        allow_delegation=False
    )

    usa_agent = Agent(
        role="Creative American Story Writer",
        goal="Write engaging and well-written short stories",
        backstory=(
            "You are a skilled American storyteller who excels at crafting compelling narratives. "
            "You take creative topics and transform them into engaging short stories that captivate readers. "
            "Your stories are concise yet captivating, with strong character development and imaginative plots."
        ),
        llm=llm_usa,
        verbose=True,
        allow_delegation=False
    )

    # Define Tasks
    generate_topic_task = Task(
        description=(
            "Generate ONE creative and interesting story topic.\n"
            "Respond with JUST the topic, nothing else. No greetings, no explanations, just the topic.\n"
            "Focus on imaginative, engaging, and unique story ideas that would make great short stories."
        ),
        expected_output="A single creative story topic as plain text",
        agent=eu_agent
    )

    write_story_task = Task(
        description=(
            "Write a creative short story based on the topic generated by the EU agent.\n"
            "Make the story engaging and well-written. Keep it concise but captivating.\n"
            "Focus on character development, imaginative plot, and an engaging narrative."
        ),
        expected_output="A complete short story with beginning, middle, and end",
        agent=usa_agent,
        context=[generate_topic_task]  # pulls the EU agent's output as context
    )

    # Create and run the Crew
    crew = Crew(
        agents=[eu_agent, usa_agent],
        tasks=[generate_topic_task, write_story_task],
        process=Process.sequential,
        verbose=True,
        memory=False
    )

    print("Starting multi-site agentic framework...")

    result = crew.kickoff()

    # Print results
    print("\n=== EU Topic ===")
    print(generate_topic_task.output)

    print("\n=== Final Story ===")
    print(result)


if __name__ == "__main__":
    main()
