[project]
name = "arqit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.1.1",
    "crewai>=0.28.8",
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
]

